### ISSUE TITLE
Does not compile after most recent merge.

### ISSUE THREAD

**Issue by dejo7374** [rclynch/Lynch_CSCI2270_Finalproject#5]
There is an error from the most recent merge that breaks the adjusted buildVector function. It is a minor mistake from merging the function that adds the temp node to the vector. The function defines the temp node as "temp" but line 452 in MovieTree.cpp attempts to pass "node" to push_back() while "node" hasn't been defined.

**Comment by rclynch** [comment]
Thank you for the check, wasn't able to get to it in time but thank you for fixing it!
